"""HTML report generator using Jinja2."""
from __future__ import annotations

from jinja2 import Template

from daxops.scoring.bronze import CriterionResult
from daxops.health.rules import Finding

HTML_TEMPLATE = Template("""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>DaxOps Report</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 900px; margin: 2em auto; padding: 0 1em; color: #1a1a1a; }
  h1 { border-bottom: 3px solid #0078d4; padding-bottom: 0.3em; }
  h2 { color: #0078d4; margin-top: 1.5em; }
  .tier { padding: 1em; border-radius: 8px; margin: 1em 0; font-size: 1.2em; font-weight: bold; }
  .gold { background: #fff3cd; border: 2px solid #ffc107; }
  .silver { background: #e8e8e8; border: 2px solid #adb5bd; }
  .bronze { background: #f8d7da; border: 2px solid #cd7f32; }
  .none { background: #f8f9fa; border: 2px solid #dee2e6; }
  .criterion { padding: 0.5em 0; border-bottom: 1px solid #eee; }
  .score-2 { color: #28a745; } .score-1 { color: #ffc107; } .score-0 { color: #dc3545; }
  .detail { color: #666; font-size: 0.9em; margin-left: 1.5em; }
  .finding { padding: 0.3em 0; }
  .sev-ERROR { color: #dc3545; font-weight: bold; }
  .sev-WARNING { color: #e67e00; }
  .sev-INFO { color: #0078d4; }
  table { border-collapse: collapse; width: 100%; margin: 1em 0; }
  th, td { text-align: left; padding: 0.5em; border-bottom: 1px solid #eee; }
  th { background: #f8f9fa; }
</style>
</head>
<body>
<h1>DaxOps Report</h1>

<div class="tier {{ tier_class }}">{{ tier_text }}</div>

{% for tier_name, criteria in tiers %}
<h2>{{ tier_name }} — {{ criteria | sum(attribute='score') }}/{{ criteria | sum(attribute='max_score') }}</h2>
<table>
<tr><th>Criterion</th><th>Score</th><th>Details</th></tr>
{% for c in criteria %}
<tr class="criterion">
  <td class="score-{{ c.score }}">{{ '✅' if c.score == 2 else '⚠️' if c.score == 1 else '❌' }} {{ c.name }}</td>
  <td>{{ c.score }}/{{ c.max_score }}</td>
  <td>{{ c.description }}{% for d in c.details %}<div class="detail">{{ d }}</div>{% endfor %}</td>
</tr>
{% endfor %}
</table>
{% endfor %}

{% if findings %}
<h2>Health Check Findings ({{ findings | length }})</h2>
<table>
<tr><th>Severity</th><th>Rule</th><th>Object</th><th>Message</th></tr>
{% for f in findings %}
<tr class="finding">
  <td class="sev-{{ f.severity.value }}">{{ f.severity.value }}</td>
  <td>{{ f.rule }}</td>
  <td>{{ f.object_path }}</td>
  <td>{{ f.message }}</td>
</tr>
{% endfor %}
</table>
{% endif %}

<footer style="margin-top:2em;color:#999;font-size:0.8em">Generated by DaxOps</footer>
</body>
</html>""")


def generate_html_report(
    bronze: list[CriterionResult],
    silver: list[CriterionResult],
    gold: list[CriterionResult],
    findings: list[Finding] | None = None,
) -> str:
    b_score = sum(c.score for c in bronze)
    s_score = sum(c.score for c in silver)
    g_score = sum(c.score for c in gold)

    bronze_pass = b_score >= 10
    silver_pass = bronze_pass and s_score >= 10
    gold_pass = silver_pass and g_score >= 8

    if gold_pass:
        tier_class, tier_text = "gold", "🥇 Gold Tier Achieved"
    elif silver_pass:
        tier_class, tier_text = "silver", "🥈 Silver Tier Achieved"
    elif bronze_pass:
        tier_class, tier_text = "bronze", "🥉 Bronze Tier Achieved"
    else:
        tier_class, tier_text = "none", f"⬜ No Tier — Bronze needs {10 - b_score} more points"

    return HTML_TEMPLATE.render(
        tier_class=tier_class,
        tier_text=tier_text,
        tiers=[("Bronze", bronze), ("Silver", silver), ("Gold", gold)],
        findings=findings or [],
    )
