/// Core transactional table — one row per order line
table Sales
	lineageTag: a1b2c3d4-0001

	/// Total revenue from all completed sales
	measure 'Total Revenue' = SUM(Sales[Net Amount])
		formatString: £#,##0
		displayFolder: Revenue
		lineageTag: m-001

	/// Number of distinct orders placed
	measure 'Order Count' = DISTINCTCOUNT(Sales[Order ID])
		formatString: #,##0
		displayFolder: Orders
		lineageTag: m-002

	/// Average revenue per order, calculated as Total Revenue / Order Count
	measure 'Avg Order Value' = DIVIDE([Total Revenue], [Order Count], 0)
		formatString: £#,##0.00
		displayFolder: Revenue
		lineageTag: m-003

	measure 'YTD Revenue' = TOTALYTD([Total Revenue], 'Date'[Date])
		formatString: £#,##0
		lineageTag: m-004

	measure 'Revenue LY' = CALCULATE([Total Revenue], SAMEPERIODLASTYEAR('Date'[Date]))
		lineageTag: m-005

	measure 'Revenue Growth %' = DIVIDE([Total Revenue] - [Revenue LY], [Revenue LY], 0)
		lineageTag: m-006

	/// Quantity of items sold across all orders
	measure 'Units Sold' = SUM(Sales[Quantity])
		formatString: #,##0
		displayFolder: Orders
		lineageTag: m-007

	column 'Net Amount'
		dataType: decimal
		formatString: £#,##0.00
		summarizeBy: sum
		lineageTag: c-001

	column 'Order ID'
		dataType: string
		lineageTag: c-002

	column Quantity
		dataType: int64
		formatString: #,##0
		summarizeBy: sum
		lineageTag: c-003

	column 'Order Date'
		dataType: dateTime
		formatString: dd/MM/yyyy
		lineageTag: c-004

	column 'Customer ID'
		dataType: int64
		lineageTag: c-005

	column 'Product ID'
		dataType: int64
		lineageTag: c-006

	column SalesKey
		dataType: int64
		lineageTag: c-007

	partition Sales = m
		mode: import
		source =
			let
				Source = Sql.Database("server", "db"),
				Sales = Source{[Schema="dbo",Item="Sales"]}[Data]
			in
				Sales
